### PR TITLE
Modify the content of email for experiment status change

### PR DESCRIPTION
**Pull request by nhatlinh300401**
Issue: https://github.com/DiscoverCCRI/portal_v1/issues/22
I modified the content of the email for the experiment status change and add the space for comment (image attached below).

image

### CODE REVIEW

**Comment by 17jhagan** [comment]
From today's discussion: What is the purpose of the REQUEST field in this email? If there is not any benefit to keeping it, we should consider removing this value.

**Comment by nhatlinh300401** [comment]
After testing with other types of portal emails, the section REQUEST is same as the MESSAGE so I think we could get rid of the section REQUEST.

Also, I have 2 questions:
- From the email above, I think we should put the URL section at the bottom and remove the section Notification/Message since we have the section MESSAGE and they have same content. Do you think that's a good message format?
- From the last discussion about the JSON format of resource definition, I think we could change it to the listing format (image attached below).

image

**Comment by 17jhagan** [comment]
From our discussion yesterday: 

- See where REQUEST is filled with anything other than "None". Maybe we can consider removing the REQUEST field for those emails that have "None" values. 
- Change the "Notification/Message" title to "Operator Comments" to make this more clear.
- Moving the URL to the bottom of the email sounds fine to me.
- For Question number 2 (though not relevant to this issue), we should aim to have a set of drop-down options for users to set up their resource definitons. This should allow them to select currently defined resources and associated sensors they would like to interface with.

Thanks Linh! Once you've made some changes to the email body, comment with another screenshot of how it's looking!

**Comment by nhatlinh300401** [comment]
Hi @17jhagan , I'm sorry for late respond since last week I was out of town. I will make the modify and get back to you later today.

**Comment by nhatlinh300401** [comment]
Hey @17jhagan , I attached new look of email for experiment status below. For the last point in your last reply, I saw Bailey created an issue for resource definition. Does that include the dropdown set?

image

**Comment by 17jhagan** [comment]
Hi Linh, I think this looks good. I'm going to merge this PR. About the resource definition dropdown, I believe this is captured in the issue that Bailey made last week, but you should coordinate with Bailey to double-check.

**Pull request merged**
